site_name: 'Bulk RNAseq data analysis'
nav:
    - 'Course Introduction': index.md
    - 'Setup': 02_setup.md
    - 'Experimental planning': 03_experimental_planning.md
    - 'Data Explanation': 04_data_explanation.md
    - 'Preprocessing': 05_preprocessing.md
    - 'RNAseq counts':
        - 'Count matrix': 06a_count_matrix.md
        - 'Normalization': 06b_count_normalization.md
    - 'Exploratory Analysis': 07_exploratory_analysis.md
    - 'Differential Expression': 
        - 'Design formula': 08a_contrast_design.md
        - 'DESeq2': 08b_DEA.md
        - 'Hypothesis testing': 08c_hypothesis_testing.md
        - 'Visualization': 08d_DEA_visualization.md
    - 'Functional Analysis': 
        - 'Gene annotation': 09a_FA_genomic_annotation.md
        - 'Over representation analysis': 09b_FA_overrepresentation.md
        - 'Class scoring': 09c_FA_GSEA.md
    - 'Summarized workflow': 10_summarized_workflow.md
    
use_directory_urls: false
docs_dir: develop
site_dir: docs
plugins:
extra_css:
    - extra.css
theme: 
    name: material
    logo: img/sandbox1.png
    favicon: img/sandbox1.png
    palette:
      primary: grey
      accent: cyan
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
extra:
  homepage: https://hds-sandbox.github.io/